### ISSUE TITLE
Update github actions CI config to include ghc 8.10.3?

### ISSUE THREAD

**Issue by jhrcek** [kowainik/.github#13]
Thank you for the great post about haskell CI via github actions.
https://kodimensional.dev/github-actions

Now that stackage lts-17.0 with support for GHC 8.10.3 was released, I'm updating CI config in some of my haskell projects to include it. It would be nice if the https://github.com/kowainik/.github/blob/main/workflow-templates/ci.yml linked from the above blogpost was updated to include that GHC version. Also I noticed that https://github.com/actions/setup-haskell action has been archived and this action is now recommended as a maintained for of that https://github.com/haskell/actions

**Comment by chshersh** [comment]
Hi @jhrcek, thanks for the kind words!

Yes, the old action was archived and doesn't support GHC-8.10.3. To use the latest GHC, you also need to update the Setup Haskell action itself to the one you've pointed. This should work if you want to use the latest GHC.

We are slowly moving to the usage of this new action, and it works so far. But we haven't tested it long enough to update the template and blog post. And there are some issues suggesting that the action name would most likely change. The action also will contain several breaking changes in the newer versions. So updating the template now will still require more work, probably soon. But we will do this when we have time. However, if you want to submit a PR with updates, feel free to do it, we would appreciate that a lot!

**Comment by chshersh** [comment]
We've updated the template to the latest versions of everything, so this issue can be closed 🙂

**Comment by jhrcek** [comment]
Thank you :+1:
