### ISSUE TITLE
Missing .stylish-haskell.yaml

### ISSUE THREAD

**Issue by steshaw** [kowainik/.github#15]
Hi, I noticed a 404 from [CONTRIBUTING](https://github.com/kowainik/.github/blob/main/CONTRIBUTING.md) which refers to a `.stylish-haskell.yaml` that does not exist here.

https://github.com/kowainik/.github/blob/main/.stylish-haskell.yaml

Looks like one should just be dropped in from [org](https://github.com/kowainik/org/blob/main/.stylish-haskell.yaml)?

**Comment by vrom911** [comment]
That's right! Thanks for noticing 🤗
